# Generated by Django 3.2 on 2024-03-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='Driver_Id',
            new_name='Driver',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='Staff_Id',
            new_name='Staff',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='User_Id',
            new_name='Users',
        ),
    ]
