# Generated by Django 3.2 on 2024-03-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0002_auto_20240314_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
