# Generated by Django 3.2 on 2024-03-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0003_auto_20240314_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='Availability',
            field=models.CharField(choices=[('Ava', 'Select your Availability'), ('Mrng', 'Morning Shift:7:00 AM to 3:00 PM'), ('Day', 'Day Shift:10:00 AM to 6:00 PM'), ('Eve', 'Evening Shift:3:00 PM to 11:00 PM'), ('Night', 'Night Shift:11:00 PM to 7:00 AM')], default='Ava', max_length=5),
        ),
    ]
