# Generated by Django 3.2 on 2024-03-18 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0004_alter_driverprofile_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('k', 'Select your Gender'), ('M', 'Male'), ('F', 'Female')], default='k', max_length=5)),
                ('status', models.BooleanField(default=0)),
                ('Admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
