# Generated by Django 3.2 on 2024-03-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0005_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_ID', models.IntegerField()),
                ('Timestamp', models.IntegerField()),
                ('Eye_Hull', models.IntegerField()),
                ('Lip_Hull', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='data_submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_ID', models.IntegerField()),
                ('Timestamp', models.IntegerField()),
                ('Blink', models.IntegerField()),
                ('Yawn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trips',
            fields=[
                ('Trip_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Booking_Status', models.CharField(choices=[('k', 'Select your Status'), ('A', 'Accepted'), ('D', 'Declined')], default='k', max_length=5)),
                ('Departure', models.CharField(choices=[('k', 'Select your Location'), ('H', 'Hyderabad'), ('M', 'Mumbai'), ('D', 'Delhi'), ('K', 'Kolkata')], default='k', max_length=5)),
                ('Destination', models.CharField(choices=[('k', 'Select your Location'), ('H', 'Hyderabad'), ('M', 'Mumbai'), ('D', 'Delhi'), ('K', 'Kolkata')], default='k', max_length=5)),
                ('User_username', models.CharField(default=0, max_length=50)),
                ('Driver_Username', models.CharField(default=0, max_length=50)),
                ('Trip_status', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
