# Generated by Django 3.2 on 2024-03-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0007_remove_trips_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='Departure',
            field=models.CharField(choices=[('k', 'Select your Departure'), ('H', 'Hyderabad'), ('M', 'Mumbai'), ('D', 'Delhi'), ('K', 'Kolkata')], default='k', max_length=5),
        ),
        migrations.AlterField(
            model_name='trips',
            name='Destination',
            field=models.CharField(choices=[('k', 'Select your Destination'), ('H', 'Hyderabad'), ('M', 'Mumbai'), ('D', 'Delhi'), ('K', 'Kolkata')], default='k', max_length=5),
        ),
    ]
