# Generated by Django 3.2 on 2024-03-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0008_auto_20240323_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='Booking_Status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='trips',
            name='Trip_status',
            field=models.BooleanField(default=0),
        ),
    ]
