# Generated by Django 3.2 on 2024-03-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0009_auto_20240323_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='Trip_status',
            field=models.BooleanField(),
        ),
    ]
