# Generated by Django 3.2 on 2024-03-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0010_alter_trips_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='Booking_Status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trips',
            name='Trip_status',
            field=models.IntegerField(),
        ),
    ]
