# Generated by Django 3.2 on 2024-03-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0011_auto_20240323_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='Driver_Username',
            new_name='Drivername',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='User_username',
            new_name='Username',
        ),
    ]
