# Generated by Django 3.2 on 2024-03-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0013_remove_trips_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
