# Generated by Django 3.2 on 2024-03-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0014_trips_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
