# Generated by Django 3.2 on 2024-03-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0015_alter_trips_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='status',
            field=models.IntegerField(choices=[('0', 'Pending'), ('1', 'Declined'), ('2', 'Accepted')], default='0'),
        ),
    ]
