# Generated by Django 3.2 on 2024-03-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0016_alter_trips_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='Drivername',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trips',
            name='status',
            field=models.IntegerField(choices=[('0', 'Pending'), ('1', 'Declined'), ('2', 'Accepted'), ('3', 'Completed')], default='0'),
        ),
    ]
