# Generated by Django 3.2 on 2024-03-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognition', '0017_auto_20240331_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Declined'), ('2', 'Accepted'), ('3', 'Completed')], default='0', max_length=50),
        ),
    ]
